const path = {
  login: "/login",
  home: "/home",
  register: "/register",
  products: "/products",
  pages: "/pages",
  blog: "/blog",
  shop: "/shop",
  contact: "/contact",
  checkout: "/checkout",
  detail: "/detail/:id",
  billingAddress: "/checkout/billing-address",
  history: "/history",
  listLike: "/list-like",
  detailOrder: "/detail-order/:id",
  forgot: "/forgot-password",
  info: "/info",
  oauth2: "/oauth2/redirect",
};
export default path;
